apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  ports:
    - port: 8000
  selector:
    app: django
    tier: app
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      volumes:
        - name: django-app-data
          persistentVolumeClaim:
            claimName: django-app-pvc
      containers:
        - image: amarkanth/k8s_recipe:latest
          name: app
          command: ["sh", "/app/entrypoint.sh"]
          volumeMounts:
            - name: django-app-data
              mountPath: /vol/web
          env:
            - name: DB_HOST
              value: django-postgres
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DEBUG
              value: "1"