http {
    upstream backends {
        server djangoapp1:8000;
        server djangoapp2:8000;
        server djangoapp3:8000;
        server djangoapp4:8000;
    }

    server {
        listen 80;
        listen [::]:80;

        server_name practicepurpose.xyz;
        server_tokens off;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://backends;
        }
    }
}

events {}
